package miniJava.SyntacticAnalyzer;

public enum TokenType 
{INT,BOOL,VOID,
CLASS,PUBLIC,PRIVATE,STATIC,
IF,ELSE,WHILE,TRUE,FALSE,NULL,
THIS,NEW,RETURN,

ASSIGN,INTLIT,ID,

 /* Operators */
PLUS,MULT,SUBT,DIV,NEG,
AND,OR,GT,LT,EQUAL,GTE,LTE,NOTEQ,NOT,

LPAREN,RPAREN,LBRACK,RBRACK,LBRACE,RBRACE,
COMMA,SEMICOL,DOT,
EOT,ERROR
}
